# Generated by Django 4.0.4 on 2022-05-06 13:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('TwitterLike', '0002_comment_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='retweet',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
